# Generated by Django 3.1.7 on 2021-04-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210429_2129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
